name: AMApp

extensions:
- name: dapr
  log-level: debug
  config: appconfig
  components-path: "./components/tye/"
# - name: zipkin
# - name: elastic
  # logPath: ./.logs

services:

- name: postgres
  image:  postgres
  env:
  - name: POSTGRES_PASSWORD
    value: P@ssw0rd
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
  tags:
  - apis

- name: productapi
  project: Product/ProductService.Api/ProductService.Api.csproj
  env:
  - name: ConnectionStrings__postgres
    value: Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=${env:POSTGRES_PASSWORD};
  bindings:
  - port: 7003
  tags:
  - apis

- name: customerapi
  project: Customer/CustomerService.Api/CustomerService.Api.csproj
  env:
  - name: ConnectionStrings__postgres
    value: Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=${env:POSTGRES_PASSWORD};
  bindings:
  - port: 7004
  tags:
  - apis

- name: settingapi
  project: Setting/SettingService.Api/SettingService.Api.csproj
  env:
  - name: ConnectionStrings__postgres
    value: Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=${env:POSTGRES_PASSWORD};
  bindings:
  - port: 7005
  tags:
  - apis

- name: identityapp
  project: Identity/Identity.csproj
  bindings:
  - port: 7001
    protocol: https
  tags:
  - id

- name: webblazor
  project: WebBlazor/Server/WebBlazor.Server/WebBlazor.Server.csproj
  bindings:
  - port: 7002
    protocol: https

- name: webapigatewayapp
  project: AppGateway/AppGateway.csproj
  bindings:
  - port: 7000
  tags:
  - apis
- name: ocelotwebapigatewayapp
  project: OcelotAPIGateway/OcelotAPIGateway.csproj
  bindings:
  - port: 7050
  tags:
  - apis
