// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using ProductService.Infra.Data;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ProductService.Infra
{
    [DbContext(typeof(MainDbContext))]
    public partial class MainDbContextModel : RuntimeModel
    {
        static MainDbContextModel()
        {
            var model = new MainDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static MainDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
